import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "./components/providers";
import Appbar from "./components/Appbar";
import SignInPanel from "./components/signInPanel";
import { ToastContainer } from "react-toastify";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Cuattro Vistas",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col">
        <Providers>
          <Appbar>
            <SignInPanel/>
          </Appbar>
          <main className="flex-grow min-h-screen">{children}</main>
          <Footer />
          <ToastContainer/>
        </Providers>
      </body>
    </html>
  );
}

